include $(TOPDIR)/rules.mk

LUCI_TITLE:=Diagnosis
LUCI_DEPENDS:=+luci-base +ysyslogd
LUCI_PKGARCH:=all

PKG_LICENSE:=GPL-2.0-or-later

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
